site_name: LibX Wiki
site_url: https://moddingx.github.io/WikiX
repo_name: ModdingX/LibX
repo_url: https://github.com/ModdingX/LibX
use_directory_urls: false

theme: windmill

markdown_extensions:
  - codehilite:
      noclasses: true
      use_pygments: true
      pygments_style: igor

extra:
  logo: logo.png
  version: "<span onClick=\"window.open('https://moddingx.org/discord')\">Discord</span>"

nav:
  - Home: index.md
  - First Steps: first_steps.md
  - Configs:
    - Home: config/index.md
    - Key Types: config/key_types.md
  - The LibX Registration System:
    - Home: registration/index.md
    - Registry Transformers: registration/transformers.md
    - Registry Tracking: registration/tracking.md
  - ModInit:
    - Home: modinit/index.md
    - Codecs: modinit/codecs.md
    - Registration: modinit/registration.md
