site_name: ModdingX Wiki
site_url: https://moddingx.github.io/WikiX
repo_name: ModdingX
repo_url: https://github.com/ModdingX/
edit_uri: https://github.com/ModdingX/WikiX/edit/master/docs/
use_directory_urls: false

theme:
  name: material
  custom_dir: theme
  palette:
    scheme: default
    primary: teal
    accent: pink
  logo: assets/logo_bg.png
  favicon: assets/logo.png
  
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://moddingx.org/discord
    - icon: fontawesome/brands/github
      link: https://github.com/ModdingX/
    - icon: minecraft/curseforge
      link: https://github.com/ModdingX/LibX
    - icon: minecraft/modrinth
      link: https://modrinth.com/mod/libx

markdown_extensions:
  - codehilite:
      noclasses: true
      use_pygments: true
      pygments_style: igor
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details

nav:
  - Home: index.md
  - LibX:
    - Home: libx/index.md
    - First Steps: libx/first_steps.md
    - Configs:
      - Home: libx/config/index.md
      - Key Types: libx/config/key_types.md
    - The LibX Registration System:
      - Home: libx/registration/index.md
      - Registry Transformers: libx/registration/transformers.md
      - Registry Tracking: libx/registration/tracking.md
    - The LibX Datagen System:
      - Home: libx/datagen/index.md
    - SandBox:
      - Home: libx/sandbox/index.md
      - Datagen: libx/sandbox/datagen.md
    - ModInit:
      - Home: libx/modinit/index.md
      - Codecs: libx/modinit/codecs.md
      - Registration: libx/modinit/registration.md
