site_name: LibX Wiki
repo_name: noeppi-noeppi/LibX
repo_url: https://github.com/noeppi-noeppi/LibX
use_directory_urls: false

theme: windmill

markdown_extensions:
  - codehilite:
      noclasses: true
      use_pygments: true
      pygments_style: igor

extra:
  logo: logo.png
  version: "<span onClick=\"window.open('https://discord.gg/NfwG6txUN6')\">Discord</span>"

nav:
  - Home: index.md
  - First Steps: first_steps.md
  - Registration:
    - Home: registration/index.md
    - Base Classes: registration/base_classes.md
    - Advanced: registration/advanced.md
  - Configs:
    - Home: config/index.md
    - Key Types: config/key_types.md
  - ModInit:
    - Home: modinit/index.md
    - Registration: modinit/registration.md
    - Codecs: modinit/codecs.md
   